// example/javascript-react/src/pages/SearchTvShow.js
import React from 'react';
import Select from 'react-select/async';
import _ from "lodash";
import * as Service from '../services';

export default class SearchTvShow extends React.Component {

  state = {
    value: ''
  };

  getOptions = (input) => {
    return Service.searchTvShow(input)
  };

  render() {
    const Option = (props) => {
      if(props.isDisabled) return null
      return (
          <div className="row resultSearch">
            <button className={"btn btn-default btnSearch"} style={{width: '100%'}} onClick={() => props.setValue(props.data)}>
            <div className="col-md-3">
              {props.data.image && <img width="300px" src={`${props.data.image}`}/>}
            </div>
            <div className="col-md-9">
              <div className="TvResult">
                <h3>{props.data.title} ({props.data.source})</h3>
                <p>
                  {_.truncate(props.data.description, {'length': 120})}
                </p>
              </div>
            </div>
            </button>
          </div>
      )
    }
    return <Select
      name="form-field-name"
      onChange={value => {
        Service.addTvShow(value.id).then(() => this.setState({value}))
      }}
      inputValue={this.state.inputValue}
      blurInputOnSelect={false}
      onInputChange={inputValue => this.setState({ inputValue })}
      loadOptions={this.getOptions}
      placeholder={"Search a tv show"}
      components={{Option}}
    />
  }
}

// example/javascript-angular/src/app/search-tv-show/search-tv-show.component.ts
import {Component, EventEmitter, OnInit, Output, ViewChild} from '@angular/core';
import {IOptions} from "tslint";
import {AppServicesService} from "../app-services.service";
import {SelectComponent} from 'ng-select';


@Component({
  selector: 'app-search-tv-show',
  templateUrl: './search-tv-show.component.html',
  styleUrls: ['./search-tv-show.component.scss']
})
export class SearchTvShowComponent implements OnInit {

  options: Array<IOptions>;
  @Output() onSelected = new EventEmitter<any>();
  @ViewChild("mySelect") mySelect: SelectComponent;

  constructor(private appService: AppServicesService) {
  }

  ngOnInit() {
  }

  onNoOptionsFound(event) {
    this.searchTvShows(event);
  }

  selected(event) {
    this.mySelect.clear();

    this.appService.addTvShow(event.id)
      .subscribe(() => {
        this.onSelected.emit(event);
      });
  }

  private searchTvShows(inputSearch: string) {
    this.appService.searchTvShows(inputSearch)
      .subscribe(options => {
        this.options = options.map(o => {
          return {
            ...o,
            value: o.id,
            label: o.title
          }
        });
      });
  }
}

<ng-select
  #mySelect
  [options]="options"
  [allowClear]="true"
  (noOptionsFound)="onNoOptionsFound($event)"
  (selected)="selected($event)"
>
  <ng-template #optionTemplate
               let-option="option">
    <div>
      <button class="btn btn-default btnSearch" style="width: 100%">
        <div class="row resultSearch">
          <div class="col-md-3">
            <img width="300px" *ngIf="option.image" [src]="option.image"/>
          </div>
          <div class="col-md-9">
            <div class="TvResult">
              <h3>{{option.title}} ({{option.source}})</h3>
              <p>
                {{option.description | slice:0:120}}
              </p>
            </div>
          </div>
        </div>
      </button>
    </div>
  </ng-template>
</ng-select>
