// example/example-spring/javascript-react/src/pages/Layout.js
import React from "react";
import * as Service from "../services";
import { Link } from 'react-router-dom';

const Layout = props => (
  <div className="container">
    <nav className="navbar navbar-default">
      <div className="container-fluid">
        <div className="navbar-header">
          <button type="button" className="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span className="sr-only">Toggle navigation</span>
            <span className="icon-bar"></span>
            <span className="icon-bar"></span>
            <span className="icon-bar"></span>
          </button>
          <Link to={"/"} className="navbar-brand"><img src={`${props.rootPath}img/logo.png`} /></Link>
        </div>
        <div id="navbar" className="navbar-collapse collapse">
          <ul className="nav navbar-nav navbar-right">
            <li><Link to={"/login"} onClick={ e => Service.logout()}>{props.user.userId} <span className="glyphicon glyphicon-off"></span></Link></li>
          </ul>
        </div>
      </div>
    </nav>
    {props.children}
  </div>
);

export default Layout;

// example/javascript-angular/src/app/layout/layout.component.ts
import {Component, OnInit} from '@angular/core';
import {AppServicesService} from "../app-services.service";
import {ActivatedRoute, Router} from "@angular/router";
import {User} from "../model/User";

@Component({
  selector: 'app-layout',
  templateUrl: './layout.component.html',
  styleUrls: ['./layout.component.scss']
})
export class LayoutComponent implements OnInit {
  currentUser: User;

  constructor(private router: Router, private appService: AppServicesService, private route: ActivatedRoute) {
  }

  ngOnInit() {
    this.route.data.subscribe(data => {
      if (data && data.consumer && data.consumer.userId)
        this.currentUser = data.consumer;
    });
  }

  logout() {
    this.appService.logout();
  }

}

<app-izanami-provider [children]="izanamiProviderChildren" fetchFrom="/api/izanami" [debug]="true">
  <ng-template #izanamiProviderChildren>
    <div class="container">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a routerLink="/" class="navbar-brand"><img src="/assets/img/logo.png"/></a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">

              <li><a routerLink="/login" (click)="logout()" *ngIf="currentUser">{{currentUser.userId}} <span
                class="glyphicon glyphicon-off"></span></a></li>
            </ul>
          </div>
        </div>
      </nav>

      <router-outlet></router-outlet>

    </div>
  </ng-template>
</app-izanami-provider>
