// example/example-spring/javascript-react/src/pages/MyTvshows.js
import React from 'react';
import * as Service from "../services";
import SearchTvShow from './SearchTvShow'
import Layout from './Layout';
import {Experiment, Variant} from 'react-izanami';
import {Link} from 'react-router-dom';
import _ from "lodash";

export default class MyTvShows extends React.Component {

  remove = id => e => {
    Service.removeTvShow(id);
  };

  markAsWon = () => {
    Service.notifyWon("mytvshows:gotoepisodes:button");
  };

  render() {
    return (
      <Layout user={this.props.user}>
        <div className="row" >
          <div className="col-md-12" >
            <div className="row">
              <div className="col-md-12">
                <h2>My Tv Shows</h2>
                <SearchTvShow />
                {this.props.user.shows.map(({image, title, description, id}) =>
                  <div className="media" key={`shows-${id}`}>
                    <div className="media-left media-middle">
                        <img className="media-object" width="540px" src={`${image}`} />
                    </div>
                    <div className="media-body">
                      <h3 className="media-heading">{title}</h3>
                      <Experiment path={"mytvshows:gotoepisodes:button"} notifyDisplay="/api/izanami/experiments/displayed" >
                        <Variant id={"A"}>
                          <Link to={`/tvshow/${id}`} onClick={this.markAsWon} className="btn pull-right" alt="consulter"><i className="fa fa-eye"></i></Link>
                        </Variant>
                        <Variant id={"B"}>
                          <Link to={`/tvshow/${id}`} onClick={this.markAsWon} className="btn pull-right" alt="consulter"><i className="glyphicon glyphicon-chevron-right"></i></Link>
                        </Variant>
                      </Experiment>
                      <button type="button" className="btn pull-right" onClick={this.remove(id)} alt="supprimer"><i className="glyphicon glyphicon-trash"/></button>
                      <p className="description">{_.truncate(description, {length:350})}</p>
                    </div>
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      </Layout>
    )
  }
}

// example/example-spring/javascript-angular/src/app/my-tv-shows/my-tv-shows.component.ts
import {Component, OnInit} from '@angular/core';
import {Show} from "../model/Show";
import {AppServicesService} from "../app-services.service";
import {ActivatedRoute} from "@angular/router";
import {User} from "../model/User";

@Component({
  selector: 'app-my-tv-shows',
  templateUrl: './my-tv-shows.component.html',
  styleUrls: ['./my-tv-shows.component.scss']
})
export class MyTvShowsComponent implements OnInit {

  currentUser: User;
  shows: Show[];

  constructor(private appServices: AppServicesService, private route: ActivatedRoute) {
  }

  ngOnInit() {
    this.route.data.subscribe(
      data => {
        if (data && data.consumer && data.consumer.userId) {
          this.currentUser = data.consumer;
          this.shows = this.currentUser.shows;
        }
      }
    );
  }

  markAsWon() {
    this.appServices.notifyWon("mytvshows:gotoepisodes:button");
  }

  remove(show: Show) {
    this.appServices.removeTvShow(show.id)
      .subscribe(() =>
        this.reload()
      );
  }

  private reload() {
    this.appServices.me()
      .subscribe(user => {
        this.currentUser = user;
        this.shows = this.currentUser.shows;
      });
  }

  onSelected() {
    this.reload();
  }

}

<div class="row">
  <div class="col-md-12">
    <div class="row">
      <div class="col-md-12">
        <h2>My Tv Shows</h2>
        <app-search-tv-show (onSelected)="onSelected($event)"></app-search-tv-show>

        <div *ngFor="let show of (shows || [])" class="media">
          <div class="media-left media-middle">
            <img class="media-object" width="540px" [src]="show.image"/>
          </div>
          <div class="media-body">
            <h3 class="media-heading">{{show.title}}</h3>

            <ng-template appExperiment path="mytvshows:gotoepisodes:button"
                         notifyDisplayPath="/api/izanami/experiments/displayed" variant="A" [debug]="true">
              <a routerLink="/tvshow/{{show.id}}" (click)="markAsWon" class="btn pull-right"><i
                class="fa fa-eye"></i></a>
            </ng-template>
            <ng-template appExperiment path="mytvshows:gotoepisodes:button"
                         notifyDisplayPath="/api/izanami/experiments/displayed" variant="B" [debug]="true">
              <a routerLink="/tvshow/{{show.id}}" (click)="markAsWon" class="btn pull-right"><i
                class="glyphicon glyphicon-chevron-right"></i></a>
            </ng-template>

            <button type="button" class="btn pull-right" (click)="remove(show)" alt="supprimer"><i
              class="glyphicon glyphicon-trash"></i>
            </button>
            <p class="description">{{show.description | slice:0:120}}</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
